services:

    mongo-express:
      restart: always
      build:
        context: ./mongo-express
        args:
          - ME_VERSION=${ME_VERSION}
          - ME_CONFIG_MONGODB_SERVER=${ME_CONFIG_MONGODB_SERVER}
          - ME_CONFIG_MONGODB_PORT=${ME_CONFIG_MONGODB_PORT}
          - ME_CONFIG_MONGODB_ENABLE_ADMIN=${ME_CONFIG_MONGODB_ENABLE_ADMIN}
          - ME_CONFIG_BASICAUTH_USERNAME=${ME_CONFIG_BASICAUTH_USERNAME}
          - ME_CONFIG_BASICAUTH_PASSWORD=${ME_CONFIG_BASICAUTH_PASSWORD}
          - ME_CONFIG_SITE_BASEURL=${ME_CONFIG_SITE_BASEURL}
          - ME_CONFIG_SITE_HOST=${ME_CONFIG_SITE_HOST}
          - ME_CONFIG_SITE_PORT=${ME_CONFIG_SITE_PORT}
          - ME_CONFIG_SITE_TITLE=${ME_CONFIG_SITE_TITLE}
      environment:
        - ME_CONFIG_MONGODB_SERVER=${ME_CONFIG_MONGODB_SERVER}
        - ME_CONFIG_MONGODB_PORT=${ME_CONFIG_MONGODB_PORT}
        - ME_CONFIG_MONGODB_ENABLE_ADMIN=${ME_CONFIG_MONGODB_ENABLE_ADMIN}
        - ME_CONFIG_BASICAUTH_USERNAME=${ME_CONFIG_BASICAUTH_USERNAME}
        - ME_CONFIG_BASICAUTH_PASSWORD=${ME_CONFIG_BASICAUTH_PASSWORD}
        - ME_CONFIG_SITE_BASEURL=${ME_CONFIG_SITE_BASEURL}
        - ME_CONFIG_SITE_HOST=${ME_CONFIG_SITE_HOST}
        - ME_CONFIG_SITE_PORT=${ME_CONFIG_SITE_PORT}
        - ME_CONFIG_SITE_TITLE=${ME_CONFIG_SITE_TITLE}
      ports:
        - "${ME_PORT}:8081"
      depends_on:
        - mongo
      networks:
        - backend
